### ISSUE TITLE
Printing the middle of the earth

### ISSUE THREAD

**Issue by mrwulff** [furrysalamander/mini-map-maker#1]
https://prnt.sc/xn42lh
[USGS_LPC_NV_LasVegas_QL1_2016_16220_LAS_2018.zip](https://github.com/furrysalamander/mini-map-maker/files/5874453/USGS_LPC_NV_LasVegas_QL1_2016_16220_LAS_2018.zip)
[downloadlist.txt](https://github.com/furrysalamander/mini-map-maker/files/5874457/downloadlist.txt)

**Comment by jeyeager65** [comment]
When I was trying to figure out my own problem, some debugging showed that somehow in asc_parse.gen_stls_from_ascs, lowest_value was getting set to -9999.  I made a change to filter out values less than zero from d that I think fixed it, but couldn't verify due to my issues generating a reasonable sized STL.

**Comment by furrysalamander** [comment]
I think I found the fix for this, just trying to get caught up on homework so I have time to implement the patch.

**Comment by furrysalamander** [comment]
This should be resolved with my latest commit.  If it's still a problem feel free to leave a comment.
